name: backend-ci-workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - name: Install Dependency
        run: cd starter/backend &&  pipenv install

      - name: Run Lint
        run: cd starter/backend &&  pipenv run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - name: Install Dependency
        run: cd starter/backend &&  pipenv install

      - name: Run Test
        run: cd starter/backend &&  pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - name: Install Dependency
        run: cd starter/backend &&  pipenv install

      - name: Run Test
        run: cd starter/backend &&  pipenv run serve