name: frontend-cd-workflow

on:
  push:
    branches:
      - master
  
  workflow_dispatch:

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node Js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependency
        run: cd starter/frontend &&  npm ci 

      - name: Run Test
        run: cd starter/frontend &&  npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build docker image
        runs: |
          docker build -t first-image:latest .